config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :targets do
    get :reachable, on: :collection
  end

  resources :appliances do
    get :all_appliances, on: :collection
  end

end

app/models/appliance.rb
class Appliance < ActiveRecord::Base
  has_many :targets, dependent: :destroy

  validates :name,     uniqueness: true,
                       presence:   true

  validates :customer, presence:   true

  def target_count
    targets.count
  end

end

app/models/target.rb
class Target < ActiveRecord::Base
  belongs_to :appliance

  validates :appliance_id, presence:   true

  validates :hostname,     presence:   true,
                           uniqueness: true

  validates :address,      presence:   true,
                           format:     {with: Resolv::IPv4::Regex}

  def reachable?
    Net::Ping::TCP.new(address,nil,0.1).ping?
  end
end

app/controllers/appliances_controller.rb
class AppliancesController < ApplicationController

  def all_appliances
    appliances = Hash[ *Appliance.find_each(batch_size:100).map { |app| [app.name.split(".")[0].titleize, app.target_count] }.flatten ]
    render :json => appliances
  end

  def show
    @appliance = Appliance.find(params[:id])
  end
  
  def index
    @appliances = Appliance.all
  end

  def new
    @appliance = Appliance.new
  end

  def create
    @appliance = Appliance.new(appliance_params)
    if @appliance.save
      flash.notice = "New Ship Added Successfully"
      redirect_to @appliance
    else
      flash.alert = @appliance.errors.full_messages
      render "new"
    end
  end

  def edit
    @appliance = Appliance.find(params[:id])
  end

  def update
    @appliance = Appliance.find(params[:id])
    if @appliance.try(:update,appliance_params)
      flash.notice = "Data Updated Successfully"
      redirect_to @appliance
    else
      flash.alert = @appliance.errors
      render "edit"
    end
  end

  private

  def appliance_params
    params.require(:appliance).permit(:name, :customer)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController

  #GET /targets/reachable
  def reachable
    targets = Hash[ *Target.find_each(batch_size:100).map { |target| [target.address, target.reachable?] }.flatten ]
    render :json => targets
  end

  def index
  end

end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/appliances/edit.html.haml
%h1 Update Space Ship Data

%div.appliance-form
  = form_for @appliance, url: {action: "update"}, html: {role: "form", class: "form-horizontal"} do |f|
    = render :partial => "shared/appliance_form", :locals => {:f => f, :appliance => @appliance}
    %div.form-group
      = f.submit "Update Ship Data", :class => "btn btn-default"

=render :partial => "shared/navigation"

app/views/appliances/index.html.haml
%h1
  Starship Fleet

%div#top_display
  %div#fleet_list
    %h3 Current Ships
    - @appliances.each do |appliance|
      %p
        %span#shipname
          =link_to "#{appliance.name.split('.')[0].titleize}", "#{edit_appliance_path(appliance.id)}"
        driven by 
        %span#shippilot #{appliance.customer}

  %div#chart
    %h3 Target Numbers per Ship
    %canvas#targetspership(width="800" height="386")

%div#links
  =link_to "Add New Ship", "#{new_appliance_path}", :class => "add_ship" 

  =render :partial => "shared/navigation"

%script(type="text/javascript")
  buildTargetsSpreadChart();

app/views/appliances/new.html.haml
%h1 Add New Space Ship to the Fleet

%div.appliance-form
  = form_for @appliance, url: {action: "create"}, html: {role: "form", class: "form-horizontal"} do |f|
    = render :partial => "shared/appliance_form", :locals => {:f => f, :appliance => @appliance}
    %div.form-group
      = f.submit "Add Data", :class => "btn btn-default"

=render :partial => "shared/navigation"

app/views/appliances/show.html.haml
%h1 #{@appliance.name}

- if flash[:notice]
  %div.notice
    = flash[:notice]

%p
  Driver: 
  %span#shippilot #{@appliance.customer}

=render :partial => "shared/navigation"

app/views/home/index.html.haml
%h1
  Fleet Stats

=image_tag 'spaceship1.png'

%p
  %a{:href => "#{targets_path}"} View Overall Target Reachability
%p
  %a{:href => "#{appliances_path}"} View All Ships

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Starship Fleet Stats
    =stylesheet_link_tag 'application'
    =javascript_include_tag 'application'
    =favicon_link_tag 'toaster.png'
    =csrf_meta_tags

  %body
    =yield

app/views/shared/_appliance_form.html.haml
%div.form-group
  = f.label :name, "Ship Name", :class => "col-sm-4 control-label"
  %div.col-sm-6
    = f.text_field :name, :class => "form-control"
  %ul#error
    - unless @appliance.errors[:name].empty?
      - @appliance.errors[:name].each do |msg|
        %li
          = msg
%div.form-group
  = f.label :customer, "Pilot", :class => "col-sm-4 control-label"
  %div.col-sm-6
    = f.text_field :customer, :class => "form-control"
  %ul#error
    - unless appliance.errors[:customer].empty?
      - appliance.errors[:customer].each do |msg|
        %li
          = msg

app/views/shared/_navigation.html.haml
%div#home-nav
  %ul
    %li= link_to "Home", "#{root_path}"
    %li= link_to "Fleet", "#{appliances_path}"
    %li= link_to "Target Data", "#{targets_path}"

app/views/targets/index.html.haml
%h1
  How many Targets are currently within reach?

%canvas#myChart(width="400" height="400")

%div#legend
  %div
    %p Targets for all ships in our fleet:
  %div#reachable-key
  %div#label-key Reachable
  %br
  %div#unreachable-key
  %div#label-key Unreachable

=render :partial => "shared/navigation"

%script(type="text/javascript")
  buildPieChart();